version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notes_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: express_backend
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - DATABASE_URL=postgresql://postgres:password@postgres-db:5432/notes_db
    depends_on:
      - postgres-db
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: react_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
